name: chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_core: ^2.15.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  datetime_picker_formfield_new: ^2.1.0
  uuid: ^3.0.7
  encrypt: ^5.0.1
  webcrypto: ^0.5.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "images/conversation.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

